CSID-DGU/2020-1-CECD3-KingBaDa-2

- docker-elk/logstash/Dockerfile
> add logstash plugin

- DIS/client/src/components/SideMenu.vue
- DIS/client/src/data/graphData.js
- DIS/client/src/views/Dashboard.vue
- DIS/client/src/views/admin/AdminHome.vue
> edit admin page

- DIS/server/routes/api/elastic/index.js
- docker-elk/logstash/pipeline/logstash.conf
logstash host안나오도록 수정하고 elastic get수정하였습니다.
> logstash config수정, elastic/get부분 전체 넘겨주도록 수정

- DIS/client/src/views/Login.vue
- DIS/server/routes/api/elastic/index.js
- docker-elk/logstash/pipeline/logstash.conf
> 원하는 데이터와 검색어를 넘기면 해당 검색결과의 원하는 데이터 부분만 출력하는 부분 작성

- DIS/client/src/components/test.vue
- DIS/client/src/views/Login.vue
- DIS/server/routes/api/elastic/index.js
> elastic 검색 부분 완성

- DIS/client/src/components/SideMenu.vue
- DIS/client/src/views/Dashboard.vue
sidebar avatar, logout button 추가
> sidebar edit

- DIS/client/src/views/Login.vue
- DIS/client/src/views/admin/AdminHome.vue
- DIS/server/routes/api/admin/index.js
- DIS/server/routes/api/index.js
add sampleAPIs for admin page
add simple get domain API
add simple post domain API
> add sampleAPIs and simple get domain API

- DIS/client/src/components/NoticeComp.vue
- DIS/client/src/views/admin/AdminHome.vue
> Add datepicker, domainAPI

- DIS/server/routes/api/admin/index.js
add domain delete API (adminpage domain/job page)
> add domain delete API

- DIS/client/src/views/Login.vue
- DIS/server/routes/api/elastic/index.js
restfil api url을 규칙에 맞게 변경하였고 통계치를 계산하는 elastic-cal을 추가했습니다.
Please delete options that are not relevant.
> Restful api url변경, 최대,최소,평균,누적계산 elastic-cal추가

- DIS/server/routes/api/elastic/index.js
elastic 경로 글로벌ip로 수정
Please delete options that are not relevant.
> elastic 경로 수정

- DIS/server/routes/api/elastic/index.js
elastic 주석변경
Please delete options that are not relevant.
> elastic 주석 변경

- DIS/client/src/views/admin/AdminHome.vue
> edit adminHome

- DIS/server/routes/api/admin/index.js
change db connection
connenction -> connection pool
> Admin api connection pool

- DIS/client/src/views/admin/AdminHome.vue
> edit data format

- DIS/server/routes/api/elastic/index.js
Restful API에 맞게 post를 get으로 수정했습니다.
> elastic 라우터 post->get 변경

- DIS/server/routes/api/elastic/index.js
- docker-elk/logstash/pipeline/logstash.conf
elasticsearch index를 테스트에서 날짜에따라 변경함에 따라 Restful API index부분을 수정했습니다.
> logstash index 날짜로변경, Restful API index부분 수정

- DIS/client/src/views/admin/AdminHome.vue
> Add device registration

- DIS/server/routes/api/elastic/index.js
- docker-elk/logstash/pipeline/logstash.conf
API POST로 변경하고 logstash 인덱스를 iotlog - %날짜로 변경
> API post로 변경 logstash index변경

- docker-elk/docker-compose.yml
logstash, elasticsearch 힙사이즈 수정(1GB -> 10GB)
> logstash, elasticsearch 힙사이즈 수정

- .gitignore
- DIS/server/routes/api/admin/index.js
> edit Admin api

- DIS/client/src/views/admin/AdminHome.vue
> edit admin UI

- DIS/server/config/config.js
- DIS/server/routes/api/admin/index.js
> edit admin api (graph data)

- DIS/client/src/views/admin/AdminHome.vue
> Add devicename, Job api
